import { TestCase } from '../types';

export const TEST_CASES: TestCase[] = [
  {
    id: 'case_adult_loss',
    name: 'Test Case 1: Adult Weight Loss (Overweight Male)',
    badge: 'Clinical Standard',
    scenario: 'Male, 35 years old, 180 cm, 95 kg. Moderately active. Seeks safe 0.5 kg/week reduction toward 80 kg. Zero contraindications.',
    expectedSummary: 'BMI 29.3 · Devine IBW 73.0 kg · BMR ~1,880 kcal · TDEE ~2,914 kcal · Target ~2,364 kcal/day · Green Flag',
    data: {
      unitSystem: 'metric',
      name: 'David Miller',
      age: 35,
      gender: 'male',
      heightCm: 180,
      weightKg: 95,
      targetWeightKg: 80,
      goal: 'lose',
      activityLevel: 'moderate',
      weeklyPaceKg: 0.5,
      selectedConditions: [],
      otherConditionText: '',
      confirmedRiskAcknowledgement: true,
    },
  },
  {
    id: 'case_pediatric_growth',
    name: 'Test Case 2: Adolescent Evaluation (16yo Female)',
    badge: 'Pediatric Growth',
    scenario: 'Female, 16 years old, 162 cm, 54 kg. Lightly active. Maintain weight. Screened for developmental growth chart considerations.',
    expectedSummary: 'BMI 20.6 (Pediatric Percentile Notice) · Devine IBW 54.2 kg · BMR ~1,326 kcal · TDEE ~1,824 kcal · Developmental Advisory',
    data: {
      unitSystem: 'metric',
      name: 'Maya Lin',
      age: 16,
      gender: 'female',
      heightCm: 162,
      weightKg: 54,
      targetWeightKg: 54,
      goal: 'maintain',
      activityLevel: 'light',
      weeklyPaceKg: 0.5,
      selectedConditions: [],
      otherConditionText: '',
      confirmedRiskAcknowledgement: true,
    },
  },
  {
    id: 'case_red_flag_risk',
    name: 'Test Case 3: Clinical Red Flag (Pregnancy / Nursing)',
    badge: 'High Clinical Alert',
    scenario: 'Female, 29 years old, 165 cm, 76 kg. Sedentary. Currently pregnant/nursing. Attempts weight loss deficit.',
    expectedSummary: 'Red Flag Triggered · Caloric Restriction Contraindicated · Mandatory Physician Oversight Gate Enforced',
    data: {
      unitSystem: 'metric',
      name: 'Sarah Connor',
      age: 29,
      gender: 'female',
      heightCm: 165,
      weightKg: 76,
      targetWeightKg: 65,
      goal: 'lose',
      activityLevel: 'sedentary',
      weeklyPaceKg: 0.5,
      selectedConditions: ['pregnancy_breastfeeding'],
      otherConditionText: '',
      confirmedRiskAcknowledgement: false,
    },
  },
];
